---
title: "Digital Behavioral Data"
subtitle: "Winter semester 2022/23"
author: 
  - name: Christoph Adrian 
    url: https://twitter.com/chrdrn
    affiliation: Lehrstuhl für Kommunikationswissenschaft
    affiliation-url: https://www.kowi.rw.fau.de/person/christoph-adrian/
bibliography: references.bib
csl: content/apa.csl
nocite: |
 @engel2021, @engel2021a, @gesis-leibniz-institutfürsozialwissenschaften, @salganik2018, @atteveldt2021
---

## Contents

In this seminar, students will be introduced to working with digital behavioral data (DBD). DBD refers to digital traces of human behavior that are knowingly or unknowingly left in online environments (e.g., social media, messengers, entertainment media, or digital collaboration tools). These rich data are increasingly available to social scientific research in the public interest but can also be used to derive strategic insights for business decisions. Students will learn how to work with DBD alongside the entire research process, from data collection, preprocessing and analysis, to reporting and provision (e.g., via open science tools). Students will first get a comprehensive overview of the ways in which DBD can be collected (e.g., API scraping, usage logging, mock-up virtual environments, or data donations), as well as the requirements for data protection, research ethics, and data quality. Afterwards, students will practice and apply their newly gained knowledge in small projects on use cases from media and communication research. In doing so, they learn about key computational methods via which large digital behavioral datasets (e.g., texts, images, usage behavior logs) can be processed and analyzed. By completing this module, participants will get an up-to-date overview and practical insights into how to harness the potential of observational data traces to better understand media users' behavior in digital environments.


## Students will

-   overview and understand central opportunities of DBD and accompanying challenges for data collection and preprocessing

-   evaluate the strengths and weaknesses of different ways of collecting DBD

-   get to know and understand central requirements for data protection, research ethics, and data quality

-   get to know and overview key computational social science methods to analyze DBD

-   practice and apply knowledge on DBD, statistics, and data analysis in small projects of their own


## Recommended prerequisites

-   Interest in social scientific perspectives on media, communication, and digital technologies.

-   Basic knowledge of working with statistical software such as Stata, R, Python, or SPSS is required.

-   Students are recommended, but not required, to also visit the lecture Data Science: Foundations, Tools, Applications in Socio-Economics and Marketing.


## Schedule

Below is the scheudle for the current semester. 

| Session             | Datum                        | Topic                                           |
|------------------|---------------------|-------------------------------------------------------------|
| [**1**]{.smallcaps} | [**26.10.2022**]{.smallcaps} | [**Kick-Off Session**]{.smallcaps}              |
| 2                   | 02.11.2022                   | DBD: Introduction & Overview                    |
| 3                   | 09.11.2022                   | DBD: Data collection process in focus           |
| 4                   | 16.11.2022                   | API-Access (I): *Twitter*                       |
| 5                   | 23.11.2022                   | API-Access (II): *YouTube*                      |
| 6                   | 30.11.2022                   | API-Access (II): *Reddit*                       |
| 7                   | 07.12.2022                   | Webscraping: *TikTok*                           |
| 8                   | 14.12.2022                   | ESM: *m-path*                                   |
| -                   | -                            | *CHRISTMAS BREAK*                               |
| 9                   | 12.01.2023                   | Data Donations                                  |
| 10                  | 19.01.2023                   | Mock-Up-Virtual Environments                    |
| 11                  | 26.01.2023                   | Open Science                                    |
| 12                  | 02.02.2023                   | ***Guest Lecture: Linking DBD & Survey data***  |
| 13                  | 09.02.2023                   | Closing Session: Recap, Evaluation & Discussion |


## Copyright
This content is licensed under a [GPL-3.0 License](https://www.gnu.org/licenses/gpl-3.0.en.html).


